repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        pass_filenames: true
        args: ["--line-length=120"]
  #  - repo: https://gitlab.com/pycqa/flake8
  #    rev: 3.8.4
  #    hooks:
  #      - id: flake8
  #        pass_filenames: true
  #        exclude: __init__.py
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        pass_filenames: true
